### ISSUE TITLE
How to register custom components in vue-formio

### ISSUE THREAD

**Issue by github-weiwei** [formio/vue#10]
Can anyone tell me how to solve it ? Thank you.

**Comment by kamsi** [comment]
@github-weiwei well, I would love to get an answer to this one as well.
In the meantime I figured out sth that kind of works:

```javcript
import { Form } from 'vue-formio'; // this one is needed so that we have Formio in global scope
import BaseComponent from 'vue-formio/node_modules/formiojs/components/base/Base';
import Vue from 'vue/dist/vue.esm';

var MyVueComponent = Vue.extend({
    name: 'MyVueComponent',
    props: {
        component: null
    },
    template: '<div v-bind:id="component.key">{{ component.someProp }}</div>'
});

class MyComponent extends BaseComponent {
    build() {
        super.build();
        let element = super.getElement();
        var instance = new MyVueComponent({
            propsData: {
                component: this.component,
            },
            el: element
        });
        instance.$mount();
        element.appendChild(instance.$el);
    }
}

Formio.registerComponent('mycomponent', MyComponent);
`

Now, if you add mycomponent to your form definition you should see a result.

**Comment by github-weiwei** [comment]
Thank you  I try.

**Comment by rohanrp** [comment]
Answer is a bit outdated as the code has changed since 2018

Here's a sample ratings component based on a radio button

Custom component class
`import { Formio } from 'vue-formio'
import Vue from 'vue'
import { generateUniqueId } from '../../models/form-utils'

const RatingsComponent = Vue.extend({
  props: {
    component: {
      type: Object,
      default: () => {}
    },
    styles: {
      type: String,
      default: ''
    }
  },
  mounted: function() {
    var css = document.createElement('style')
    css.type = 'text/css'
    css.setAttributeNode(document.createAttribute('scopped'))
    css.appendChild(document.createTextNode(this.styles))
    this.$el.appendChild(css)
  },
  methods: {
    handleClick(value, values) {
      values.forEach((option) => {
        option.checked = false
        option.id = generateUniqueId()
        option.checked = option.value <= value
      })
    }
  },
  template: `
    <div>
        <fieldset class="rating">
            <div v-for="(item) in component.values" :key="item.id" >
                <input type="radio" :name="item.value" :value="item.value" :checked="item.checked"/>
                <label :for="item.value" :title="item.value" @click="handleClick(item.value, component.values)"></label>
            </div>
        </fieldset>
    </div>
  `
})

const RadioComponent = Formio.Components.components.radio

export class RatingFormIOComponent extends RadioComponent {
  attach(element) {
    const styles = this.styling('.rating > div')
    var instance = new RatingsComponent({
      propsData: {
        component: this.component,
        styles
      },
      el: element
    })

    instance.$mount()
    return super.attach(instance.$el)
  }

  styling(id) {
    return `
    ${id} {
        float:left;
    }
    
    ${id}:not(:checked) > input {
        position: absolute;
        clip: rect(0, 0, 0, 0);
        height: 0;
        width: 0;
        overflow: hidden;
        opacity: 0;
    } 
    
    ${id}:not(:checked) > label {
        float:right;
        padding:0 .1em;
        overflow:hidden;
        white-space:nowrap;
        cursor:pointer;
        font-size:200%;
        line-height:1.2;
        color:#ddd;
        text-shadow:1px 1px #bbb, 2px 2px #666, .1em .1em .2em rgba(0,0,0,.5);
    }
    
    ${id}:not(:checked) > label:before {
        content: '★ ';
    }
    
    ${id} > input:checked ~ label {
        color: #f70;
        text-shadow:1px 1px #c60, 2px 2px #940, .1em .1em .2em rgba(0,0,0,.5);
    }
    
    ${id}:not(:checked) > label:hover,
    ${id}:not(:checked) > label:hover ~ label {
        color: gold;
        text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
    }
    
    ${id} > input:checked + label:hover,
    ${id} > input:checked + label:hover ~ label,
    ${id} > input:checked ~ label:hover,
    ${id} > input:checked ~ label:hover ~ label,
    ${id} > label:hover ~ input:checked ~ label {
        color: #ea0;
        text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
    }
    
    ${id} > label:active {
        position:relative;
        top:2px;
        left:2px;
    }

      `.replace(/\s+/g, '')
  }
}
`

register the componet globally in formio
`import { Formio } from 'vue-formio'
import { RatingFormIOComponent } from './rating-formio'

export const registerCustomComponents = () => {
  Formio.Components.addComponent('rating', RatingFormIOComponent)
}`


call the register method before form render

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
