### ISSUE TITLE
Error while embedding Form / FormBuilder

### ISSUE THREAD

**Issue by davidfenko** [formio/vue#11]
Hi,

I'm attempting to embed the FormBuilder / Form, following the instructions you provided in the readme.

I'm trying to include this in a fresh Laravel application. I created a new component, and included it on the page. I then receive the following error:

![screen shot 2018-08-27 at 13 48 27](https://user-images.githubusercontent.com/3885421/44658149-fcedd600-a9ff-11e8-834d-01e48aa6059b.png)

The error occurs when I import the module:
```javascript
<template>
    <h1>Hello!</h1>
</template>

<script>
    import { Form } from 'vue-formio'; // <- If I remove this, it works fine...
    export default {
        name: 'viewer',
        components: { Form },
    }
</script>
```

If I remove the import statement, everything works fine, so the project setup itself should be okay as well.

Am I missing something in how I should package the components together?

Cheers

**Comment by Bes79** [comment]
Hi! I have the same error as you also on clean laravel. But if I remove import it does not help me at all. All the same, tell me how you fixed the issue.

**Comment by tokp** [comment]
I have the same error. Remove import not helps.

**Comment by tokp** [comment]
I found an issue when combine electronjs and webpack and it cause in webpack 'electron-renderer' target config. My workaround was add next lines to webpack renderer config:
```
let rendererConfig = {
  ...
  externals: ['vue', 'vue-formio'],
  resolve {
    ...
    alias: {
      ...
      mainFields: ['browser', 'main']
    }
  }
}
```

**Comment by nyirongojr** [comment]
@tokp, i am not able to find the 'webpack renderer config' file so that i can try your work around. Where is it located in a laravel project

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
