### ISSUE TITLE
lose stylesheet

### ISSUE THREAD

**Issue by zhangrenjian** [formio/vue#18]
has not style

**Comment by lizhiying61f** [comment]
@zhangrenjian me too, Did you solve this problem？

**Comment by zhangrenjian** [comment]
npm install bootstrap  and import  into project ,看你名字也不该是老外啊，哈哈，安装引入bootstrap就行了

**Comment by lizhiying61f** [comment]
@zhangrenjian 哈哈，我码字的时候也纠结了一下的

**Comment by zhangrenjian** [comment]
509634685，我qq，有问题可以问我

**Comment by lizhiying61f** [comment]
@zhangrenjian 谢辣~

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
