### ISSUE TITLE
Data binding

### ISSUE THREAD

**Issue by Bdestasio33** [formio/vue#20]
How is the data bound in the form. Specifically is it two way and reactive. Does changing field inputs update the form automatically?

**Comment by goatandsheep** [comment]
Just listen for the `submit` event. Not using 2-way binding is better for accessibility, speed, and more.

**Comment by goatandsheep** [comment]
[It looks like it should be reactive](https://github.com/formio/vue-formio/blob/f592d9fbec11cbbd36bcbe6ead2c8c67bdd527ee/src/components/Form.ts#L46)

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
