### ISSUE TITLE
Select component not rendering correctly.

### ISSUE THREAD

**Issue by DA37708** [formio/vue#22]
The component’s select list is showing and there are two input boxes slightly overlaying on another. 

Below is an example that will fail

"components":[
{"label":"Park","placeholder":"Enter the name of the part","allowMultipleMasks":false,"showWordCount":false,"showCharCount":false,"autofocus":true,"tableView":true,"alwaysEnabled":false,"type":"textfield","input":true,"key":"name","defaultValue":"","validate":{"customMessage":"","json":""},"conditional":{"show":"","when":"","json":""},"properties":{},"tags":[],"inputFormat":"plain","encrypted":false,"customConditional":"","logic":[],"widget":{"type":""},"reorder":false},

{"label":"Location","placeholder":"Select the state the park is THIS FAILS in","mask":false,"tableView":true,"alwaysEnabled":false,"type":"select","input":true,"key":"State","defaultValue":"","validate":{"select":false,"customMessage":"","json":""},"conditional":{"show":"","when":"","json":""},"data":{"values":[{"label":"Alabama","value":"Alabama"},{"label":"Wyoming","value":"Wyoming"}]},"valueProperty":"value","selectThreshold":0.3,"encrypted":false,"properties":{},"tags":[],"lazyLoad":false,"selectValues":"","disableLimit":false,"sort":"","reference":false,"customConditional":"","logic":[],"reorder":false}
]}

**Comment by DA37708** [comment]
Please disregard this I was able to get things working

**Comment by andreabat** [comment]
HI, I think I am experiencing the same problem. How did you get thing working ?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
