### ISSUE TITLE
Form Api Post Data Binding

### ISSUE THREAD

**Issue by nathans1309** [formio/vue#24]
I have successfully loaded a form on my webpage, but there is incorrect behavior when I submit the form.  The headers show the correct data object in the body but my resource on form IO shows that I submitted blank form fields.  The response I get back is all blanks as well.
url: `https://{myhost}.form.io/eligibility/submission`
request body: `data:  {isyourGpAabovea30Ona4Pointscale: "no", areyouaUSCitizen: "yes", submit: true}`

response: 201
response body: `data: {}`

I tried the exact same url and body in postman and the behavior is correct and I receive a correct response.

here is my form io tag 
`formio(:src="formsrc"  @submit="HandleSubmit" @submitDone="HandleSubmitDone")`

**Comment by nathans1309** [comment]
I found a fix but I'm not sure it is the best way.
installed npm package `formiojs`
added `declare module "formiojs/Formio"` to src/shims-vue.d.ts

**Comment by wag110894** [comment]
Hello Nathan,

Thanks for reaching out! 
Glad to see that you were able to fix your issue. Do you believe there is an issue in the library? If so, could you please submit a pull request and we get that pulled in.

Thanks.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
