### ISSUE TITLE
Select component with numeric option values

### ISSUE THREAD

**Issue by tomislavatanasov** [formio/vue#38]
Hey, the select component acts weird when the options use numeric values.
Is there something I am missing? See attached component:

![vueformio_select_numeric_values](https://user-images.githubusercontent.com/40025834/77189023-951a4700-6adf-11ea-92da-6347654d6632.png)

`{
	"key": "exampleSelect",
	"label": "Select",
	"type": "select",
	"defaultValue": 0,
	"validate": {
		"required": true
	},
	"data": {
		"values": [
			{
				"label": "zero",
				"value": 0
			},
			{
				"label": "hundred",
				"value": 100
			}
		]
	}
}`

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
