### ISSUE TITLE
[BUG] Form component does not emit namespaced events 

### ISSUE THREAD

**Issue by nathanaelbice** [formio/vue#44]
## Environment
Please provide as many details as you can:

- Hosting type
  - [X] Form.io
  - [X] Local deployment
    - Version: 7.0.0-rc.64
- Formio.js version: N/A
- Frontend framework: Vue.js (vue-formio 4.0.4)
- Browser: Chrome
- Browser version: 84.0.4147.105

## Steps to Reproduce
1. Set a custom namespace
2. Emit a custom event from within the Form component
3. Notice that it does not emit out to the vue layer

## Expected behavior
- The event should be available in the vue app

## Observed behavior
- The event is captured by the Form component and not emitted again.
- This same bug was observed in the FormBuilder in #39

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
