### ISSUE TITLE
[BUG] Vuejs - Bootstrap 4

### ISSUE THREAD

**Issue by ChrisRAra** [formio/vue#55]
## Environment
Vuejs 2.6.12
Bootstrap Vue 2.21.1
Bootstrap 4.6.0
formio-vue

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: Vuejs 2.6.12
    - Bootstrap Vue 2.21.1
    - Bootstrap 4.6.0
    - formio-vue
- Formio.js version: Latest
- Frontend framework: VueJS
- Browser: Chrome
- Browser version: 89.0.4389.114

## Steps to Reproduce
1. Install formio
2. Import builder

## Expected behavior

Form builder to build a form and all items to display

## Observed behavior
Form builder only allows me to add one item and then constantly replaces that item instead of adding

**Comment by brendanbond** [comment]
Thanks @ChrisRAra we'll take a look

**Comment by lane-formio** [comment]
<div>Agent Lane Doughtie linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/47344">47344</a> for this issue.</div><br/>

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
