### ISSUE TITLE
[BUG] Select component rendered as search field

### ISSUE THREAD

**Issue by dschuhmann** [formio/vue#60]
## Environment

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 2.3.0  
- Formio.js version: ^4.14.0-rc.36
- Vue-formio version: 4.0.8
- Frontend framework: vue.js 
- Vue version: ^2.6.14
- Browser: Firefox, Chrome
- Browser version: Firefox 94.0.2, Chrome 96.0.4664.45 (both latest)

## Steps to Reproduce
1. Add Select component to form, populate with data (tried entering values directly as well as providing JSON)
2. Add form to vue component (via URL)
3. Navigate to select component in the form

## Expected behavior
Seeing a dropdown selection, from which the provided values can be selected.

## Observed behavior
The vue app displays a search field and renders the selectable values directly underneath it. When a value is selected, it is shown above the search field alongside a button to remove it. No dropdown selection is rendered.

The selection component is displayed correctly in the form.io preview. I also embedded the same form with the same data in the angular demo app, where it is also rendered correctly.

The fact that the form is rendering correctly in an angular app leads me to believe that the issue is with vue-formio or the way I am using it and not with formio itself. This is the first issue I am opening on github, I hope I chose an appropriate type and provided all necessary information.

## Example

Screenshot of the incorrectly rendered form. Radio component is working fine, underneath the label "Dropdown selection" a select component should be displayed. In the screenshot the form is styled with bootstrap, but I also tried it without any styling information.

<img width="258" alt="selection_formio" src="https://user-images.githubusercontent.com/95416450/144425732-f3f2adf7-5d1b-45d9-81ab-67da6a7877d3.png">

The code for the vue component.

```js
<template>
  <div>
    <h1>{{ msg }}</h1>
    <div>
      <formio
        src="http://localhost:3001/path/to/form"
        url=""
        form=""
        submission=""
        options=""
      ></formio>
    </div>
  </div>
</template>

<script>
import { Form } from 'vue-formio'

export default {
  name: 'app',
  components: { formio: Form },
  data () {
    return {
      msg: 'FormIO testing site'
    }
  }
}
</script>
```

**Comment by shuhaib-aot** [comment]
I got the same issue. when I try the form in vue it is not showing the options to select. but it showing the search field to select the option when we enter the words which include the in the option and click the enter key in keyboard it will show the option as selected. so what is the issue. but the option we can see in html when inspecting the page

**Comment by shuhaib-aot** [comment]
@travist please make it clear

**Comment by brendanbond** [comment]
Thanks @shuhaib-aot @dschuhmann we'll investigate and get this resolved

**Comment by travist** [comment]
This just seems like the styles didn't get imported correctly. This is the behavior when you do not include the "formio-full.css" in your application SASS bundle. Try adding the styles of the renderer to your application and it should appear as the normal "choices" select dropdown.
