### ISSUE TITLE
Instance of formio getting by ref is always returning null

### ISSUE THREAD

**Issue by michelveloso** [formio/vue#66]
I'm using formio with Vue 3 and TypeScript, when getting a instance of formio by ref it is always returning null.

![image](https://user-images.githubusercontent.com/346317/160262517-0d2dd8c9-a600-430c-9d65-d115f2cd30ee.png)

![image](https://user-images.githubusercontent.com/346317/160262527-6a12b7a6-d7ea-46a9-96ca-76529443a603.png)

**Comment by kiru42** [comment]
Hi,

We have the same issue here, any update?
