### ISSUE TITLE
[Question] TypeError: Right-hand side of 'instanceof' is not callable when accessing an embedded formio form from Vue app 

### ISSUE THREAD

**Issue by echo-liang** [formio/vue#69]
- Hosting type
  - [x] Form.io
  - [x] Local deployment
- Formio.js version: 4.14.5
- Frontend framework: Vue.js (v3.2.31)
- vue-formio version: 4.0.8
- vue-router version: 4.0.14
- Browser: Chrome
- Browser version:  100.0.4896.75

I'm using formio with Vue.js (v3.2.31), trying to embed a formio resource (e.g., form) into the Vue app. When executing 'npm run dev', got below error: 
![image](https://user-images.githubusercontent.com/37156357/163303270-5cd2c06e-9e48-4590-83d3-1b35fa353ecc.png)

When clicking into index.ts:3:1, it says ' Could not load content for http://localhost:3000/node_modules/vue-formio/src/index.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)', see the screenshot below:
![image](https://user-images.githubusercontent.com/37156357/163303415-a15ddac2-6c17-4a94-b258-1bd784503865.png).

## Steps to Reproduce
1. Created a sample Vue.js app by executing 'npm init vue@latest' 
2. At https://next.form.io/, created a sample form.io project that contains a form resource.
3. Installed vue-formio by executing 'npm install --save vue-formio' command
4. Trying to embed the formio form into the Vue app by follow the instruction on form.io
5. Execute 'npm run dev'
6. Access 'http://localhost:3000/' from the browser, gets the above error.

Below is the vue component using the formio resource:
```js
<template>
    <div id="app">
        <formio :src="formUrl" v-on:submit="onSubmitMethod" />
    </div>
</template>
<script>
    import { Formio } from 'vue-formio';

    export default {
        data: function() {
            // Load these from vuex or some other state store system.
            return {
                formUrl: "https://hcydsplculhonzk.form.io/crnacmpform"
            }
        },
        components: {
            formio: Formio
        },
        methods: {
            onSubmitMethod: function(submission) {
                console.log(submission);
            }
        }
    };
</script>
```
Am I missing any steps?

**Comment by echo-liang** [comment]
Figure out what causes the issue. Close the ticket.

**Comment by benjaminfaustinodssasia** [comment]
@echo-liang how do you fixed the issue?
