### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by aryanmanik013** [formio/vue#73]
![image](https://user-images.githubusercontent.com/94857374/207641868-db602100-9c1c-432f-abd2-dcf1ba98606b.png)

**Getting this issue**

**Comment by brendanbond** [comment]
Hi @aryanmanik013 can you provide us a minimal reproducible example via a JSFiddle or something similar? I'm afraid a screenshot of the error isn't going to be enough information here to help

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
