### ISSUE TITLE
vue-formio throws error on importing it to a clean project

### ISSUE THREAD

**Issue by thewalid** [formio/vue#8]
Here is the example:
https://stackblitz.com/edit/vue-e6ob7v?file=index.js

**Comment by hell-n** [comment]
Confirmed! The error occurs when importing the NPM package:
`import {FormIo} from 'vue-formio';`

**Comment by randallknutson** [comment]
I'm not sure what is going on here. Could it be because I'm using typescript and it depends on vue-class-component? The error appears to be because it is attempting to extend undefined instead of Vue.

**Comment by goatandsheep** [comment]
how do we even put the values for this example?

**Comment by show812223** [comment]
I use this way, and it work
`<template>
    <div id="app-render">
        <formio :form="myForm"></formio>
    </div>
</template>

<script>
    import { Form } from 'vue-formio';
    export default {
        name: 'app-render',
        data() {
            return {
                myForm: {
                    "display": "form",
                    "components": [
                        {
                            type: 'textfield',
                            key: 'firstName',
                            label: 'First Name',
                            placeholder: 'Enter your first name.',
                            input: true
                        },
                        {
                            type: 'textfield',
                            key: 'lastName',
                            label: 'Last Name',
                            placeholder: 'Enter your last name',
                            input: true
                        },
                        {
                            type: 'button',
                            action: 'submit',
                            label: 'Submit',
                            theme: 'primary'
                        }
                    ],
                    
                }
            }
        },
        components: {
            formio: Form
        },
    } 
</script>`

**Comment by show812223** [comment]
I use this way , and it work

> <template>
    <div id="app-render">
        <formio :form="myForm"></formio>
    </div>
</template>

> <script>

    import { Form } from 'vue-formio';
    export default {
        name: 'app-render',
        data() {
            return {
                myForm: {
                    "display": "form",
                    "components": [
                        {
                            type: 'textfield',
                            key: 'firstName',
                            label: 'First Name',
                            placeholder: 'Enter your first name.',
                            input: true
                        },
                        {
                            type: 'textfield',
                            key: 'lastName',
                            label: 'Last Name',
                            placeholder: 'Enter your last name',
                            input: true
                        },
                        {
                            type: 'button',
                            action: 'submit',
                            label: 'Submit',
                            theme: 'primary'
                        }
                    ],
                }
            }
        },
        components: {
            formio: Form
        },
    }
</script>

**Comment by booellean** [comment]
@show812223 I tried your solution with formio's FormBuilder, but it did not work. Did they ever fix this issue?

**Comment by show812223** [comment]
> @show812223 I tried your solution with formio's FormBuilder, but it did not work. Did they ever fix this issue?
@booellean I use FormBuilder, and it can work too. Maybe you have a wrong form schema ?
